name: Prepare for Docker Build&Push
description: Set up Docker Build&Push dependencies and generate Docker Tags.

inputs:
  image:
    description: image name
    required: true
  tag:
    description: Docker tag to use
    required: true
  push_latest:
    description: true will push the 'latest' tag.
    required: true
    default: "false"
  is_ingestion:
    description: true if we are building an Ingestion image, false otherwise
    required: true
    default: "false"
  release_version:
    description: OpenMetadata Release Version
  dockerhub_username:
    description: Dockerhub Username
    required: true
  dockerhub_token:
    description: Dockerhub Token
    required: true

outputs:
  tags:
    description: Generated Docker Tags
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Install Ubuntu dependencies
      if: inputs.is_ingestion == true
      shell: bash
      run: |
        sudo apt-get install -y python3-venv

    - name: Install open-metadata dependencies
      if: inputs.is_ingestion == true
      shell: bash
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install --upgrade pip
        sudo make install_antlr_cli
        make install_dev generate
    
    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        flavor:
          latest=${{ inputs.push_latest }}
        images: |
          ${{ inputs.image }}
        sep-tags: ','
        tags: |
          type=raw,value=${{ inputs.release_version }},enable=${{ inputs.is_ingestion == 'true' }}
          type=raw,${{ inputs.tag }}
